"""Add expires_at and attendee fields

Revision ID: 67f203f17c6b
Revises: a497734783d0
Create Date: 2026-09-25 15:27:00.549282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67f203f17c6b'
down_revision: Union[str, Sequence[str], None] = 'a497734783d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('attendee_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('attendee_age', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('attendee_age')
        batch_op.drop_column('attendee_name')
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
