"""remove is_active column from tickets

Revision ID: f90cac8e5ea0
Revises: 49f9e4fbb071
Create Date: 2026-07-12 13:00:11.834323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f90cac8e5ea0'
down_revision: Union[str, Sequence[str], None] = '49f9e4fbb071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_is_active'))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.create_index(batch_op.f('ix_tickets_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###
